---
- name: Install Python3 ,Docker and Dcoker compose
  hosts: docker_server
  become: yes
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: install python and docker
      yum:
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    
    - name: Install Docker Compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-{{lookup('pipe', 'uname -m') }}
        dest: /usr/local/bin/docker-compose
        mode: +x
    
    - name: Make sure a service docker running
      ansible.builtin.systemd_service:
        state: started
        enabled: true
        name: docker
    
- name: add ec2-user to docker group
  hosts: docker_server
  become: yes
  tasks:
    - name: add ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Reset ssh connection to allow user changes to affect 'current login user'
      ansible.builtin.meta: reset_connection

- name: Test docker pull
  hosts: docker_server
  tasks:
    - name: pull redis 
      ansible.builtin.command: docker pull redis