---
- name: Install Python3 and Docker
  hosts: docker_server
  become: yes
  vars: 
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: install python and docker
      yum:
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    
    - name: Make sure a service docker running
      ansible.builtin.systemd_service:
        state: started
        enabled: true
        name: docker

- name: Install Docker Compose
  hosts: docker_server
  become: yes
  tasks:
    - name: Install Docker Compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-{{lookup('pipe', 'uname -m') }}
        dest: /usr/local/bin/docker-compose
        mode: +x